name: custard CI

on:
  push:
    branches: main
  pull_request:

jobs:
  # affected:
  #   name: Find affected packages
  #   # uses: GoogleCloudPlatform/cloud-samples-tools/.github/workflows/find-affected.yaml@main
  #   uses: ./.github/workflows/find-affected.yaml
  #   with:
  #     config-file: .github/config.jsonc
  #     paths: pkg
  #     artifact-name: ${{ github.event.pull_request.head.sha }}

  submit-job:
    name: submit job
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "github.event: $x"'
        env:
          x: ${{ toJson(github.event) }}
      - run: 'echo "github.event.pull_request: $x"'
        env:
          x: ${{ toJson(github.event.pull_request) }}
      - run: 'echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"'
      - run: 'echo "github.event.head_commit.id: ${{ github.event.head_commit.id }}"'

      - name: Save inputs
        uses: davidcavazos/github-actions-testing-experiments/.github/save-inputs@main
