name: on_pull_request

on:
  push:
    branches: main
  pull_request:

jobs:
  # affected:
  #   name: Find affected packages
  #   # uses: GoogleCloudPlatform/cloud-samples-tools/.github/workflows/find-affected.yaml@main
  #   uses: ./.github/workflows/find-affected.yaml
  #   with:
  #     config-file: .github/config.jsonc
  #     paths: pkg
  #     artifact-name: ${{ github.event.pull_request.head.sha }}

  submit-job:
    name: Submit job
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "github.event: $x"'
        env:
          x: ${{ toJson(github.event) }}
      - run: 'echo "github.event.pull_request: $x"'
        env:
          x: ${{ toJson(github.event.pull_request) }}

      - name: Save job inputs
        run: |
          mkdir -p artifact/
          echo "${{ github.event.number }}" > artifact/pull-request-number
      - name: Upload inputs artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.pull_request.head.sha }}
          path: artifact/
