name: custard CI

on:
  pull_request:

jobs:
  submit-job:
    name: submit job
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "github.event: $x"'
        env:
          x: ${{ toJson(github.event) }}
      - run: 'echo "github.event.pull_request: $x"'
        env:
          x: ${{ toJson(github.event.pull_request) }}
      - run: 'echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"'
      - run: 'echo "github.event.head_commit.id: ${{ github.event.head_commit.id }}"'

      # - name: Save inputs
      #   uses: davidcavazos/github-actions-testing-experiments/save-inputs@main
