name: on_workflow_run

on:
  # workflow_dispatch:
  workflow_run:
    workflows:
      - custard CI
    types:
      - completed

env:
  CHECK_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  affected:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write # for github.rest.checks.create()
    outputs:
      pull-request-number: ${{ steps.inputs.outputs.pull-request-number }}
      paths: ${{ steps.custard.outputs.paths }}
      ci-setups: ${{ steps.custard.outputs.ci-setups }}
    steps:
      - name: Check in_progress
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            // https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run
            // https://octokit.github.io/rest.js/v21/#checks-create
            const check = await github.rest.checks.create({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                head_sha: "${{ github.event.workflow_run.head_sha }}",
                name: "affected",
                status: "in_progress",
                output: {
                  title: "Finding affected packages",
                  summary: "My summary",
                  text: "My text",
                },
            });
            return check.data;

      - name: Load inputs
        uses: davidcavazos/github-actions-testing-experiments/.github/load-inputs@main
        id: inputs
        with:
          run-id: ${{ github.event.workflow_run.id }}

      - name: Find affected packages
        uses: davidcavazos/github-actions-testing-experiments/.github/affected@main
        id: custard
        with:
          config-file: .github/config.jsonc
          commit-head: ${{ steps.inputs.outputs.commit-head }}
          commit-main: ${{ steps.inputs.outputs.commit-main }}

      - name: Check completed
        uses: actions/github-script@v7
        with:
          script: |
            // https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run
            // https://octokit.github.io/rest.js/v21/#checks-update
            const affected = ${{ fromJson(steps.custard.outputs.paths).length }};
            github.rest.checks.update({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                check_run_id: "${{ steps.check.outputs.result.id }}",
                status: "completed",
                conclusion: "success",
                output: {
                  title: `Found ${affected} packages`,
                  summary: "My summary",
                  text: "My text",
                },
            });

  test:
    needs: affected
    runs-on: ubuntu-latest
    permissions:
      checks: write # for github.rest.checks.create()
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.affected.outputs.paths) }}
    steps:
      - name: Check queued
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            // https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run
            // https://octokit.github.io/rest.js/v21/#checks-create
            const check = await github.rest.checks.create({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                head_sha: "${{ github.event.workflow_run.head_sha }}",
                name: `test - ${{ matrix.path }}`,
                status: "queued",
                output: {
                  title: "Setting up environment.",
                  summary: "My summary",
                  text: "My text",
                },
            });
            return {
              id: check.data.id,
              url: "",
            };

      - name: Checkout ${{ github.event.workflow_run.head_sha }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Check in_progress
        uses: actions/github-script@v7
        with:
          script: |
            // https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run
            // https://octokit.github.io/rest.js/v21/#checks-update
            github.rest.checks.update({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                check_run_id: "${{ steps.check.outputs.result.id }}",
                status: "in_progress",
                output: {
                  title: "Running tests",
                  summary: "My summary",
                  text: "My text",
                },
            });

      - name: Run tests
        run: sh tests.sh

      - name: Check completed
        uses: actions/github-script@v7
        with:
          script: |
            // https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run
            // https://octokit.github.io/rest.js/v21/#checks-update
            github.rest.checks.update({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                check_run_id: "${{ steps.check.outputs.result.id }}",
                status: "completed",
                conclusion: "success",
                output: {
                  title: "",
                  summary: "My summary",
                  text: "My text",
                },
            });

  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub context information
        run: |
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.event.repository.name: ${{ github.event.repository.name }}"
          echo "github.event.repository.fork: ${{ github.event.repository.fork }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.event.workflow_run.event.label.name: ${{ github.event.workflow_run.event.label.name }}"
          echo "github.event.workflow_run.head_branch: ${{ github.event.workflow_run.head_branch }}"
          echo "github.event.workflow_run.head_sha: ${{ github.event.workflow_run.head_sha }}"
          echo "github.event.workflow_run.head_repository.id: ${{ github.event.workflow_run.head_repository.id }}"
          echo "github.event.workflow_run.head_repository.fork: ${{ github.event.workflow_run.head_repository.fork }}"
          echo "github.event.workflow_run.head_repository.owner.login: ${{ github.event.workflow_run.head_repository.owner.login }}"
          echo "github.event.workflow_run.head_repository.name: ${{ github.event.workflow_run.head_repository.name }}"
      - run: echo "github.event.workflow_run.event = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github.event.workflow_run.event) }}
      - run: echo "github.event.workflow_run.head_repository = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github.event.workflow_run.head_repository) }}
      - run: echo "github.event.workflow_run = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github.event.workflow_run) }}
      - run: echo "github.event.repository = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github.event.repository) }}
      - run: echo "github.event = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github.event) }}
      - run: echo "github = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github) }}
