name: on_workflow_run

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - on_pull_request
    types:
      - completed

jobs:
  safe-job:
    if: github.event.repository.full_name == github.repository || github.event.workflow_run.conclusion == 'success'
    name: Safe workflow ${{ github.head_ref || '<main>' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write  # Permission to create a Check Run
    env:
      GH_TOKEN: ${{ github.token }}  # Needed for `gh api`
    steps:
      # https://www.kenmuse.com/blog/creating-github-checks
      # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run
      - name: Create job check
        id: check
        run: |
          CHECK_ID=$(gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f "name=Job with full permissions" \
            -f "head_sha=${{ github.event.workflow_run.head_sha || github.sha }}" \
            -f "status=in_progress" \
            -f "details_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            -f "output[title]=My title" \
            -f "output[summary]=My summary" \
            -f "output[text]=More detailed Markdown **text**" \
            /repos/${{ github.repository }}/check-runs \
            --jq ".id" \
          )
          echo "id=$CHECK_ID" >> $GITHUB_OUTPUT

      - run: echo "github.event.workflow_run.head_repository.fork = ${{ toJson(github.event.workflow_run.head_repository.fork) }}"
      - run: echo "github.event.workflow_run.head_repository = ${{ toJson(github.event.workflow_run.head_repository) }}"
      - run: echo "github.event = ${{ toJson(github.event) }}"
      - run: echo "github = ${{ toJson(github) }}"

      - if: github.event.workflow_run.head_repository.fork && github.event.workflow_run.event.label.name != 'allow'
        name: Block if not allowed
        run: |
          echo ❌ Not allowed
          gh api --method PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -f "status=completed" \
              -f "conclusion=failure" \
              /repos/${{ github.repository }}/check-runs/${{ steps.check.outputs.id }} \
          && false

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Running sensitive code
        run: |
          sh tests.sh

      # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run
      - name: ✅ Success
        run: |
          gh api --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f "status=completed" \
            -f "conclusion=success" \
            /repos/${{ github.repository }}/check-runs/${{ steps.check.outputs.id }}
