name: on_workflow_run

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - custard CI
    types:
      - completed

env:
  CHECK_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  affected:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write # for create-check and update-check
    outputs:
      pull-request-number: ${{ steps.inputs.outputs.pull-request-number }}
      paths: ${{ steps.custard.outputs.paths }}
      ci-setups: ${{ steps.custard.outputs.ci-setups }}
    steps:
      - name: Get job
        uses: davidcavazos/github-actions-testing-experiments/get-job@main
        id: job
        with:
          job-name: affected
      - name: Create check in_progress
        uses: davidcavazos/github-actions-testing-experiments/create-check@main
        id: check
        with:
          commit-sha: ${{ github.event.workflow_run.head_sha }}
          name: summary
          status: in_progress
          title: Finding affected packages
          summary: My summary
          text: My text
      - name: Load inputs
        uses: davidcavazos/github-actions-testing-experiments/load-inputs@main
        id: inputs
        with:
          run-id: ${{ github.event.workflow_run.id }}
      - run: echo "head ${{ steps.inputs.outputs.commit-head }}"
      - run: echo "main ${{ steps.inputs.outputs.commit-main }}"
      - run: echo "ctx  ${{ github.event.workflow_run.head_sha }}"
      - name: Find affected packages
        uses: davidcavazos/github-actions-testing-experiments/affected@main
        id: custard
        with:
          config-file: .github/config.jsonc
          commit-head: ${{ steps.inputs.outputs.commit-head }}
          commit-main: ${{ steps.inputs.outputs.commit-main }}
      - name: Update check success
        uses: davidcavazos/github-actions-testing-experiments/update-check@main
        with:
          check-run-id: ${{ steps.check.outputs.run-id }}
          status: completed
          conclusion: success
          title: Found ${{ steps.custard.outputs.num-paths }} package(s)

  test:
    needs: affected
    runs-on: ubuntu-latest
    permissions:
      statuses: write # for create-status and update-status
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.affected.outputs.paths) }}
    env:
      JOB_NAME: test (${{ matrix.path }})
    steps:
      - name: Get job
        uses: davidcavazos/github-actions-testing-experiments/get-job@main
        id: job
        with:
          job-name: ${{ env.JOB_NAME }}
      - name: Create status queued
        id: check
        uses: davidcavazos/github-actions-testing-experiments/create-status@main
        with:
          commit-sha: ${{ github.event.workflow_run.head_sha }}
          name: ${{ env.JOB_NAME }}
          title: Setting up environment
          details-url: ${{ steps.job.outputs.url }}

      - name: Checkout ${{ github.event.workflow_run.head_sha }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Run tests
        run: sh tests.sh

      - name: Update status success
        uses: davidcavazos/github-actions-testing-experiments/create-status@main
        with:
          commit-sha: ${{ github.event.workflow_run.head_sha }}
          name: ${{ env.JOB_NAME }}
          status: success
          details-url: ${{ steps.job.outputs.url }}

  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub context information
        run: |
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.event.repository.name: ${{ github.event.repository.name }}"
          echo "github.event.repository.fork: ${{ github.event.repository.fork }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.event.workflow_run.event.label.name: ${{ github.event.workflow_run.event.label.name }}"
          echo "github.event.workflow_run.head_branch: ${{ github.event.workflow_run.head_branch }}"
          echo "github.event.workflow_run.head_sha: ${{ github.event.workflow_run.head_sha }}"
          echo "github.event.workflow_run.head_repository.id: ${{ github.event.workflow_run.head_repository.id }}"
          echo "github.event.workflow_run.head_repository.fork: ${{ github.event.workflow_run.head_repository.fork }}"
          echo "github.event.workflow_run.head_repository.owner.login: ${{ github.event.workflow_run.head_repository.owner.login }}"
          echo "github.event.workflow_run.head_repository.name: ${{ github.event.workflow_run.head_repository.name }}"
      - run: echo "github.event.workflow_run.event = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github.event.workflow_run.event) }}
      - run: echo "github.event.workflow_run.head_repository = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github.event.workflow_run.head_repository) }}
      - run: echo "github.event.workflow_run = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github.event.workflow_run) }}
      - run: echo "github.event.repository = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github.event.repository) }}
      - run: echo "github.event = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github.event) }}
      - run: echo "github = $CONTEXT"
        env:
          CONTEXT: ${{ toJson(github) }}
