name: on_workflow_run

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - on_pull_request
    types:
      - completed

jobs:

  show-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ toJSON(github) }}"

  blocked:
    if: |
      github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.event.label.name != 'allow'
    name: Blocked, does not have 'allow' label
    runs-on: ubuntu-latest
    permissions:
      checks: write  # Permission to create a Check Run
    env:
      GH_TOKEN: ${{ github.token }}  # Needed for `gh api`
    steps:
      - name: Block PR
        run: |
          # Create check on pull request
          CHECK_ID=$(gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f "name=Job not allowed" \
            -f "head_sha=${{ github.event.workflow_run.head_sha || github.sha }}" \
            -f "output[title]=My title" \
            -f "output[summary]=My summary" \
            -f "output[text]=More detailed Markdown **text**" \
            /repos/${{ github.repository }}/check-runs \
            --jq ".id" \
          )

          # Set it as a failure
          gh api --method PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -f "status=completed" \
              -f "conclusion=failure" \
              /repos/${{ github.repository }}/check-runs/$CHECK_ID

  allowed:
    if: |
      github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.event.label.name == 'allow'
    name: Sensitive workflow ${{ github.head_ref || '<main>' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write  # Permission to create a Check Run
    env:
      GH_TOKEN: ${{ github.token }}  # Needed for `gh api`
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
      # https://www.kenmuse.com/blog/creating-github-checks
      # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run
      - name: Create check
        id: check
        run: |
          CHECK_ID=$(gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f "name=Safe authorized job" \
            -f "head_sha=${{ github.event.workflow_run.head_sha || github.sha }}" \
            -f "status=in_progress" \
            -f "output[title]=My title" \
            -f "output[summary]=My summary" \
            -f "output[text]=More detailed Markdown **text**" \
            /repos/${{ github.repository }}/check-runs \
            --jq ".id" \
          )
          echo "id=$CHECK_ID" >> $GITHUB_OUTPUT

      - name: Running sensitive code
        run: |
          sh tests.sh \
            || gh api --method PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -f "status=completed" \
              -f "conclusion=failure" \
              /repos/${{ github.repository }}/check-runs/${{ steps.check.outputs.id }}

      # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run
      - name: Mark as successful
        run: |
          gh api --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f "status=completed" \
            -f "conclusion=success" \
            /repos/${{ github.repository }}/check-runs/${{ steps.check.outputs.id }}
