name: Test

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - on_pull_request
    types:
      - completed
  workflow_dispatch: # Manual runs

jobs:
  test:
    name: 🚨 Malicious job ${{ github.head_ref || '<main>' }} 🚨
    runs-on: ubuntu-latest
    permissions:
      checks: write  # Permission to create a Check Run
    env:
      GH_TOKEN: ${{ github.token }}  # Needed for `gh api`
    steps:
      - run: echo "🚨 Malicious unauthorized code with full permissions 🚨"
