name: on_workflow_run

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - on_pull_request
    types:
      - completed

jobs:
  safe-job:
    name: 🚨 Malicious job ${{ github.head_ref || '<main>' }} 🚨
    runs-on: ubuntu-latest
    permissions:
      statuses: write  # Permission to create a commit status
    env:
      GH_TOKEN: ${{ github.token }}  # Needed for `gh api`
    steps:
      - name: GitHub context information
        run: echo "🚨 Running code with full permissions, can expose secrets!"
