name: on_workflow_run

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - on_pull_request
    types:
      - completed

jobs:
  safe-job:
    if: github.event.workflow_run.conclusion == 'success' || !github.event.workflow_run.head_repository.fork
    name: Safe workflow ${{ github.head_ref || '<main>' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write  # Permission to create a Check Run
    env:
      GH_TOKEN: ${{ github.token }}  # Needed for `gh api`
    steps:
      - name: GitHub context information
        run: |
          # github.repository_owner: ${{ github.repository_owner }}
          # github.event.repository.name: ${{ github.event.repository.name }}
          # github.sha: ${{ github.sha }}"
          # github.event.workflow_run.head_sha: ${{ github.event.workflow_run.head_sha }}"
          # github.event.workflow_run.head_repository.fork: ${{ github.event.workflow_run.head_repository.fork }}"
          echo "github.event.workflow_run = $CONTEXT_WORKFLOW_RUN"
          echo "github.event.repository = $CONTEXT_REPOSITORY"
          echo "github.event = $CONTEXT_EVENT"
          echo "github = $CONTEXT_GITHUB"
        env:
          CONTEXT_WORKFLOW_RUN: ${{ toJson(github.event.workflow_run) }}
          CONTEXT_REPOSITORY: ${{ toJson(github.event.repository) }}
          CONTEXT_EVENT: ${{ toJson(github.event) }}
          CONTEXT_GITHUB: ${{ toJson(github) }}

      # https://www.kenmuse.com/blog/creating-github-checks
      - name: Create job check
        uses: actions/github-script@v7
        id: check
        with:
          # https://octokit.github.io/rest.js/v21/#checks-create
          # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run
          script: |
            return await github.rest.checks.create({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                name: "Job with full permissions",
                head_sha: "${{ github.event.workflow_run.head_sha || github.sha }}",
                status: "in_progress",
                details_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                output: {
                  title: "My title",
                  summary: "My summary",
                  text: "More detailed Markdown **text**",
                },
            })

      - run: echo "$JSON"
        env:
          JSON: ${{ toJson(steps.check.outputs.result) }}

      - run: echo "$JSON"
        env:
          JSON: ${{ toJson(steps.check.outputs.result.data) }}

      - if: github.event.workflow_run.head_repository.fork && github.event.workflow_run.event.label.name != 'allow'
        name: Block if not allowed
        uses: actions/github-script@v7
        with:
          # https://octokit.github.io/rest.js/v21/#checks-update
          # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run
          script: |
            await github.rest.checks.update({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                check_run_id: "${{ steps.check.outputs.result.data.id }}",
                status: "completed",
                conclusion: "failure",
            })
            throw "not allowed"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Running sensitive code
        run: |
          sh tests.sh

      - name: ✅ Success
        uses: actions/github-script@v7
        with:
          # https://octokit.github.io/rest.js/v21/#checks-update
          # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run
          script: |
            github.rest.checks.update({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                check_run_id: "${{ steps.check.outputs.result.data.id }}",
                status: "completed",
                conclusion: "success",
            })