name: on_workflow_run

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - on_pull_request
    types:
      - completed

jobs:
  safe-job:
    if: github.event.workflow_run.conclusion == 'success' || !github.event.workflow_run.head_repository.fork
    name: Safe workflow ${{ github.head_ref || '<main>' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write  # Permission to create a Check Run
    env:
      GH_TOKEN: ${{ github.token }}  # Needed for `gh api`
    steps:
      - run: echo "github.repository_owner = ${{ github.repository_owner }}"
      - run: echo "github.event.repository.name = ${{ github.event.repository.name }}"
      - run: echo "github.sha = ${{ github.sha }}"
      - run: echo "github.event.workflow_run.head_sha = ${{ github.event.workflow_run.head_sha }}"
      - run: echo "github.event.workflow_run.head_repository.fork = ${{ github.event.workflow_run.head_repository.fork }}"
      - run: echo "github.event.workflow_run = $JSON"
        env:
          JSON: ${{ toJson(github.event.workflow_run) }}
      - run: echo "github.event.repository = $JSON"
        env:
          JSON: ${{ toJson(github.event.repository) }}
      - run: echo "github.event = $JSON"
        env:
          JSON: ${{ toJson(github.event) }}
      - run: echo "github = $JSON"
        env:
          JSON: ${{ toJson(github) }}

      # https://www.kenmuse.com/blog/creating-github-checks
      # https://octokit.github.io/rest.js/v21/#checks

      # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run
      - name: Create job check
        uses: actions/github-script@v7
        id: check
        with:
          script: |
            return github.rest.checks.create({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                name: "Job with full permissions",
                head_sha: "${{ github.event.workflow_run.head_sha || github.sha }}",
                status: "in_progress",
                details_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                output: {
                  title: "My title",
                  summary: "My summary",
                  text: "More detailed Markdown **text**",
                },
            }).data.id
      - run: echo "${{ steps.check.outputs.result }}"
      - run: echo "$JSON"
        env:
          JSON: ${{ steps.check.outputs.result }}

      # - name: Create job check
      #   id: check
      #   run: |
      #     CHECK_ID=$(gh api --method POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       -f "name=Job with full permissions" \
      #       -f "head_sha=${{ github.event.workflow_run.head_sha || github.sha }}" \
      #       -f "status=in_progress" \
      #       -f "output[title]=My title" \
      #       -f "output[summary]=My summary" \
      #       -f "output[text]=More detailed Markdown **text**" \
      #       /repos/${{ github.repository }}/check-runs \
      #       --jq ".id" \
      #     )
      #     echo "id=$CHECK_ID" >> $GITHUB_OUTPUT

      - if: github.event.workflow_run.head_repository.fork && github.event.workflow_run.event.label.name != 'allow'
        name: Block if not allowed
        run: |
          echo ❌ Not allowed
          $(gh api --method PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -f "status=completed" \
              -f "details_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
              -f "conclusion=failure" \
              /repos/${{ github.repository }}/check-runs/${{ steps.check.outputs.id }} \
          )
          false

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Running sensitive code
        run: |
          sh tests.sh

      # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run
      - name: ✅ Success
        run: |
          gh api --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f "status=completed" \
            -f "details_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            -f "conclusion=success" \
            /repos/${{ github.repository }}/check-runs/${{ steps.check.outputs.id }}
