name: on_workflow_run

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - on_pull_request
    types:
      - completed

jobs:

  allowed:
    name: 🚨 Malicious job ${{ github.head_ref || '<main>' }} 🚨
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚨 Running code with full permissions, can expose secrets!"
