name: on_workflow_run

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - on_pull_request
    types:
      - completed

jobs:
  safe-job:
    if: github.event.workflow_run.conclusion == 'success' || !github.event.workflow_run.head_repository.fork
    name: Safe workflow ${{ github.head_ref || '<main>' }}
    runs-on: ubuntu-latest
    permissions:
      statuses: write  # Permission to create a commit status
    env:
      GH_TOKEN: ${{ github.token }}  # Needed for `gh api`
    steps:
      - name: GitHub context information
        run: |
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.event.repository.name: ${{ github.event.repository.name }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.event.workflow_run.head_sha: ${{ github.event.workflow_run.head_sha }}"
          echo "github.event.workflow_run.head_repository.id: ${{ github.event.workflow_run.head_repository.id }}"
          echo "github.event.workflow_run.head_repository.fork: ${{ github.event.workflow_run.head_repository.fork }}"
          echo "github.event.workflow_run.head_repository: $CONTEXT_HEAD_REPOSITORY"
          echo "github.event.workflow_run = $CONTEXT_WORKFLOW_RUN"
          echo "github.event.repository = $CONTEXT_REPOSITORY"
          echo "github.event = $CONTEXT_EVENT"
          echo "github = $CONTEXT_GITHUB"
        env:
          CONTEXT_HEAD_REPOSITORY: ${{ toJson(github.event.workflow_run.head_repository) }}
          CONTEXT_WORKFLOW_RUN: ${{ toJson(github.event.workflow_run) }}
          CONTEXT_REPOSITORY: ${{ toJson(github.event.repository) }}
          CONTEXT_EVENT: ${{ toJson(github.event) }}
          CONTEXT_GITHUB: ${{ toJson(github) }}

      - name: Create job status
        uses: actions/github-script@v7
        with:
          # https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status
          # https://octokit.github.io/rest.js/v18/#repos-create-commit-status
          script: |
            github.rest.repos.createCommitStatus({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                sha: "${{ github.event.workflow_run.head_sha || github.sha }}",
                state: "pending",
                target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                description: "Please wait for job to finish, click 'Details' to see progress.",
                context: "Job result",
            });

      - if: github.event.workflow_run.head_repository.fork && github.event.workflow_run.event.label.name != 'allow'
        name: Block if not allowed
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                sha: "${{ github.event.workflow_run.head_sha || github.sha }}",
                state: "failure",
                target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                description: "Job not allowed, please add 'allow' label",
                context: "Job result",
            });
            throw "not allowed"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Running sensitive code
        run: |
          sh tests.sh

      - name: Mark status as success
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
                owner: "${{ github.repository_owner }}",
                repo: "${{ github.event.repository.name }}",
                sha: "${{ github.event.workflow_run.head_sha || github.sha }}",
                state: "success",
                target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                description: "Check passed!",
                context: "Job result",
            });