name: Test

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - authenticated
    types:
      - completed
  workflow_dispatch: # Manual runs

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write  # Permission to create a Check Run
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      # https://www.kenmuse.com/blog/creating-github-checks
      # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run
      - name: Create check
        id: check
        run: |
          CHECK_ID=$(gh api --method POST \
            /repos/${{ github.repository }}/check-runs \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f "name=Run tests" \
            -f "head_sha=${{ github.event.workflow_run.head_sha || github.sha }}" \
            -f "status=in_progress" \
            -f "output[title]=My title" \
            -f "output[summary]=My summary" \
            -f "output[text]=More detailed Markdown **text**" \
            --jq ".id" \
          )
          echo "id=$CHECK_ID" >> $GITHUB_OUTPUT

      - name: Running tests
        run: |
          sh tests.sh \
            || gh api --method PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -f "status=completed" \
              -f "conclusion=failure" \
              /repos/${{ github.repository }}/check-runs/${{ steps.check.outputs.id }}

      # https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#update-a-check-run
      - name: Mark as successful
        run: |
          gh api --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f "status=completed" \
            -f "conclusion=success" \
            /repos/${{ github.repository }}/check-runs/${{ steps.check.outputs.id }}
